export const destinations = [
  {
    id: 1,
    name: "Lijiang Old Town",
    nameZh: "丽江古城",
    slug: "lijiang-old-town",
    region: "northwest",
    description: "UNESCO World Heritage ancient town with Naxi culture, canals, and Jade Dragon Snow Mountain views",
    altitude: 2400,
    bestSeason: "Spring & Autumn",
    tags: ["UNESCO", "Ancient Town", "Naxi Culture"],
    rating: 4.8,
    reviews: 1247,
    image: "/images/destinations/lijiang.jpg",
    featured: true,
    latitude: 26.8721,
    longitude: 100.2280,
  },
  {
    id: 2,
    name: "Dali Ancient City",
    nameZh: "大理古城",
    slug: "dali-ancient-city",
    region: "central",
    description: "Historic Bai minority city between Cangshan Mountains and Erhai Lake with marble crafts",
    altitude: 1900,
    bestSeason: "Year-round",
    tags: ["Bai Culture", "Lake", "Mountains"],
    rating: 4.7,
    reviews: 982,
    image: "/images/destinations/dali.jpg",
    featured: true,
    latitude: 25.6066,
    longitude: 100.2680,
  },
  {
    id: 3,
    name: "Shangri-La",
    nameZh: "香格里拉",
    slug: "shangri-la",
    region: "northwest",
    description: "Tibetan cultural hub with monasteries, snow peaks, and highland grasslands",
    altitude: 3280,
    bestSeason: "May - October",
    tags: ["Tibetan Culture", "Buddhism", "Highland"],
    rating: 4.9,
    reviews: 756,
    image: "/images/destinations/shangri-la.jpg",
    featured: true,
    latitude: 27.8269,
    longitude: 99.7065,
  },
  {
    id: 4,
    name: "Kunming",
    nameZh: "昆明",
    slug: "kunming",
    region: "central",
    description: "Spring City with mild weather, Stone Forest, and gateway to Yunnan",
    altitude: 1890,
    bestSeason: "Year-round",
    tags: ["Capital", "Stone Forest", "Food"],
    rating: 4.5,
    reviews: 1523,
    image: "/images/destinations/kunming.jpg",
    featured: true,
    latitude: 25.0406,
    longitude: 102.7129,
  },
  {
    id: 5,
    name: "Xishuangbanna",
    nameZh: "西双版纳",
    slug: "xishuangbanna",
    region: "southwest",
    description: "Tropical paradise with Dai culture, wild elephants, and rainforests",
    altitude: 550,
    bestSeason: "November - May",
    tags: ["Tropical", "Dai Culture", "Wildlife"],
    rating: 4.6,
    reviews: 634,
    image: "/images/destinations/xishuangbanna.jpg",
    featured: true,
    latitude: 22.0115,
    longitude: 100.7979,
  },
  {
    id: 6,
    name: "Yuanyang Rice Terraces",
    nameZh: "元阳梯田",
    slug: "yuanyang-rice-terraces",
    region: "southeast",
    description: "UNESCO World Heritage rice terraces created by Hani people over 1300 years",
    altitude: 1600,
    bestSeason: "November - April",
    tags: ["UNESCO", "Photography", "Hani Culture"],
    rating: 5.0,
    reviews: 428,
    image: "/images/destinations/yuanyangtitian.jpg",
    featured: true,
    latitude: 23.1656,
    longitude: 102.7476,
  },
  {
    id: 7,
    name: "Tiger Leaping Gorge",
    nameZh: "虎跳峡",
    slug: "tiger-leaping-gorge",
    region: "northwest",
    description: "One of world's deepest gorges with spectacular hiking trails",
    altitude: 2500,
    bestSeason: "April - June, September - November",
    tags: ["Hiking", "Adventure", "Gorge"],
    rating: 4.9,
    reviews: 892,
    image: "/images/destinations/hutiaoxia.jpg",
    featured: false,
    latitude: 27.1875,
    longitude: 100.1100,
  },
  {
    id: 8,
    name: "Puzhehei",
    nameZh: "普者黑",
    slug: "puzhehei",
    region: "southeast",
    description: "Karst landscape with lotus lakes, perfect for photography and boat rides",
    altitude: 1450,
    bestSeason: "June - September (lotus blooming)",
    tags: ["Karst", "Lakes", "Photography"],
    rating: 4.7,
    reviews: 345,
    image: "/images/destinations/puzhehei.jpg",
    featured: false,
    latitude: 24.1396,
    longitude: 104.0988,
  },
]
