export const allEthnicGroups = [
  // Featured groups (already displayed)
  {
    id: "naxi",
    name: "Naxi",
    nameZh: "纳西族",
    population: "309,000",
    region: "Lijiang, Shangri-La",
    description: "Ancient matriarchal society with unique Dongba pictographic script",
    color: "from-blue-400 to-cyan-500",
    image: "/images/culture/naxi.jpg",
    highlights: ["Dongba Religion", "Ancient Music", "Matriarchal Traditions"],
  },
  {
    id: "bai",
    name: "Bai",
    nameZh: "白族",
    population: "1.9 million",
    region: "Dali, Eryuan",
    description: "Known for marble craftsmanship and the Three Pagodas",
    color: "from-purple-400 to-pink-500",
    image: "/images/culture/bai.jpg",
    highlights: ["Tie-Dye Art", "March Fair", "Architecture"],
  },
  {
    id: "yi",
    name: "Yi",
    nameZh: "彝族",
    population: "5 million",
    region: "Throughout Yunnan",
    description: "Famous for fire worship and distinctive costumes",
    color: "from-red-400 to-orange-500",
    image: "/images/culture/yi.jpg",
    highlights: ["Torch Festival", "Yi Calendar", "Fire Worship"],
  },
  {
    id: "dai",
    name: "Dai",
    nameZh: "傣族",
    population: "1.2 million",
    region: "Xishuangbanna",
    description: "Theravada Buddhist culture with Southeast Asian influences",
    color: "from-green-400 to-emerald-500",
    image: "/images/culture/dai.jpg",
    highlights: ["Water Splashing", "Peacock Dance", "Bamboo Houses"],
  },
  {
    id: "tibetan",
    name: "Tibetan",
    nameZh: "藏族",
    population: "150,000",
    region: "Shangri-La, Deqen",
    description: "Tibetan Buddhist monasteries and highland pastoral life",
    color: "from-yellow-400 to-amber-500",
    image: "/images/culture/tibetan.jpg",
    highlights: ["Buddhism", "Thangka", "Horse Racing"],
  },
  {
    id: "miao",
    name: "Miao (Hmong)",
    nameZh: "苗族",
    population: "1.1 million",
    region: "Northeast Yunnan",
    description: "Elaborate silver jewelry and embroidery traditions",
    color: "from-indigo-400 to-purple-500",
    image: "/images/culture/miao.jpg",
    highlights: ["Silver Crafts", "Reed-Pipe Dance", "Embroidery"],
  },
  {
    id: "hani",
    name: "Hani",
    nameZh: "哈尼族",
    population: "1.6 million",
    region: "Honghe, Yuanyang",
    description: "Creators of the spectacular Yuanyang Rice Terraces",
    color: "from-green-500 to-teal-500",
    image: "/images/culture/hani.jpg",
    highlights: ["Rice Terraces", "Long Table Feast", "Mushroom Houses"],
  },
  {
    id: "lisu",
    name: "Lisu",
    nameZh: "傈僳族",
    population: "703,000",
    region: "Nujiang Valley",
    description: "Mountain people with colorful festivals and rope bridges",
    color: "from-pink-400 to-rose-500",
    image: "/images/culture/lisu.jpg",
    highlights: ["Knife Ladder Festival", "Crossbow Dance", "Mountain Culture"],
  },
  // Additional ethnic groups
  {
    id: "wa",
    name: "Wa",
    nameZh: "佤族",
    population: "430,000",
    region: "Ximeng, Cangyuan",
    description: "Known for their wooden drum culture and distinctive black clothing",
    color: "from-gray-600 to-gray-700",
    image: "/images/culture/wa.jpg",
    highlights: ["Wooden Drums", "Black Clothing", "Hair Dance"],
  },
  {
    id: "lahu",
    name: "Lahu",
    nameZh: "拉祜族",
    population: "450,000",
    region: "Lancang, Menglian",
    description: "Musical people known for their gourd pipes and hunting traditions",
    color: "from-orange-400 to-red-500",
    image: "/images/culture/lahu.jpg",
    highlights: ["Gourd Pipes", "Hunting Culture", "New Year Festival"],
  },
  {
    id: "jingpo",
    name: "Jingpo",
    nameZh: "景颇族",
    population: "130,000",
    region: "Dehong Prefecture",
    description: "Warriors with elaborate sword dances and Munao festival",
    color: "from-teal-400 to-green-500",
    image: "/images/culture/jingpo.jpg",
    highlights: ["Munao Festival", "Sword Dance", "Silver Ornaments"],
  },
  {
    id: "bulang",
    name: "Bulang",
    nameZh: "布朗族",
    population: "120,000",
    region: "Xishuangbanna, Lincang",
    description: "One of the earliest tea cultivators in the world",
    color: "from-amber-500 to-yellow-600",
    image: "/images/culture/bulang.jpg",
    highlights: ["Tea Culture", "Bamboo Houses", "Tooth Dyeing"],
  },
  {
    id: "achang",
    name: "Achang",
    nameZh: "阿昌族",
    population: "40,000",
    region: "Dehong, Longyang",
    description: "Master blacksmiths famous for their Husa knives",
    color: "from-slate-500 to-zinc-600",
    image: "/images/culture/achang.jpg",
    highlights: ["Blacksmithing", "Husa Knives", "Rice Culture"],
  },
  {
    id: "pumi",
    name: "Pumi",
    nameZh: "普米族",
    population: "43,000",
    region: "Lanping, Ninglang",
    description: "Mountain dwellers with unique coming-of-age ceremonies",
    color: "from-violet-400 to-purple-500",
    image: "/images/culture/pumi.jpg",
    highlights: ["Coming-of-Age", "Mountain Life", "Sheep Breeding"],
  },
  {
    id: "nu",
    name: "Nu",
    nameZh: "怒族",
    population: "37,000",
    region: "Nujiang Valley",
    description: "Skilled in crossing rivers with zip-lines and bamboo rafts",
    color: "from-cyan-500 to-blue-600",
    image: "/images/culture/nu.jpg",
    highlights: ["River Crossing", "Fairy Festival", "Stone Houses"],
  },
  {
    id: "deang",
    name: "De'ang",
    nameZh: "德昂族",
    population: "20,000",
    region: "Dehong, Lincang",
    description: "Ancient tea farmers with unique waist drum dances",
    color: "from-lime-500 to-green-600",
    image: "/images/culture/deang.jpg",
    highlights: ["Waist Drums", "Tea Cultivation", "Water Splashing"],
  },
  {
    id: "dulong",
    name: "Dulong",
    nameZh: "独龙族",
    population: "7,000",
    region: "Dulong Valley",
    description: "Most isolated group with traditional facial tattoos (historic)",
    color: "from-emerald-500 to-teal-600",
    image: "/images/culture/dulong.jpg",
    highlights: ["Facial Tattoos", "Rainbow Blankets", "Kaquewa Festival"],
  },
  {
    id: "jinuo",
    name: "Jinuo",
    nameZh: "基诺族",
    population: "23,000",
    region: "Jinghong",
    description: "Last ethnic group officially recognized in China (1979)",
    color: "from-rose-400 to-pink-500",
    image: "/images/culture/jinuo.jpg",
    highlights: ["Sun Drum", "Temaoke Festival", "Bamboo Culture"],
  },
  {
    id: "mongol",
    name: "Mongol",
    nameZh: "蒙古族",
    population: "30,000",
    region: "Tonghai",
    description: "Descendants of Kublai Khan's soldiers with unique fishing culture",
    color: "from-sky-400 to-blue-500",
    image: "/images/culture/mongol.jpg",
    highlights: ["Fishing Culture", "Nadaam Festival", "Throat Singing"],
  },
  {
    id: "manchu",
    name: "Manchu",
    nameZh: "满族",
    population: "15,000",
    region: "Various locations",
    description: "Former Qing dynasty rulers maintaining unique customs",
    color: "from-yellow-500 to-amber-600",
    image: "/images/culture/manchu.jpg",
    highlights: ["Qipao Origins", "Shamanistic Practices", "Archery"],
  },
  {
    id: "hui",
    name: "Hui",
    nameZh: "回族",
    population: "700,000",
    region: "Throughout Yunnan",
    description: "Muslim Chinese with distinctive culinary traditions",
    color: "from-green-500 to-emerald-600",
    image: "/images/culture/hui.jpg",
    highlights: ["Islamic Culture", "Halal Cuisine", "Mosque Architecture"],
  },
  {
    id: "zhuang",
    name: "Zhuang",
    nameZh: "壮族",
    population: "1.2 million",
    region: "Wenshan Prefecture",
    description: "Largest minority in China with rich singing traditions",
    color: "from-indigo-500 to-blue-600",
    image: "/images/culture/zhuang.jpg",
    highlights: ["Folk Songs", "Brocade Weaving", "Bronze Drums"],
  },
  {
    id: "yao",
    name: "Yao",
    nameZh: "瑶族",
    population: "200,000",
    region: "Hekou, Malipo",
    description: "Mountain people known for elaborate headdresses and batik",
    color: "from-red-500 to-rose-600",
    image: "/images/culture/yao.jpg",
    highlights: ["Batik Art", "Panwang Festival", "Herbal Medicine"],
  },
  {
    id: "buyi",
    name: "Buyi",
    nameZh: "布依族",
    population: "70,000",
    region: "Luoping, Qiubei",
    description: "Master builders of stone architecture and indigo dyers",
    color: "from-blue-500 to-indigo-600",
    image: "/images/culture/buyi.jpg",
    highlights: ["Stone Houses", "Indigo Dyeing", "Ground Opera"],
  },
  {
    id: "shui",
    name: "Shui",
    nameZh: "水族",
    population: "13,000",
    region: "Fuyuan County",
    description: "People with their own ancient writing system and calendar",
    color: "from-cyan-400 to-teal-500",
    image: "/images/culture/shui.jpg",
    highlights: ["Shui Script", "Duan Festival", "Fish Farming"],
  }
];

export const featuredEthnicGroups = allEthnicGroups.slice(0, 8);